add TokenSale to deploy script
code-423n4/contracts pull request #35
Opened 2021-12-27 09:53 UTC by MrToph

# changelog
- add token sale to deploy & verify scripts

2021-12-27 12:38 UTC, HickupHH3 requested changes

2021-12-27 12:38 UTC, HickupHH3 commented on scripts/deploy.ts
> +    config.TOKEN_SALE_USDC,
tokenIn = USDC
tokenOut = ARENA

2021-12-27 12:38 UTC, HickupHH3 commented on scripts/verify.ts
> +      config.TOKEN_SALE_USDC,
here too

2021-12-27 14:06 UTC, MrToph commented on scripts/deploy.ts
> +    config.TOKEN_SALE_USDC,
thanks, fixed

2021-12-27 14:06 UTC, MrToph commented on scripts/verify.ts
> +      config.TOKEN_SALE_USDC,
fixed

2022-01-02 14:14 UTC, tabshaikh approved these changes
LGTM

2022-01-04 03:07 UTC, HickupHH3 approved these changes
LGTM.

2022-01-08 04:25 UTC, merged